name:                fp-max
version:             0.1.0.0
github:              "martinsson/fp-max"
license:             BSD3
author:              "Johan Martinsson"
maintainer:          "jm1974@hotmail.com"
copyright:           "MIT"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            dunno

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/martinsson/fp-max#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  fp-max-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - fp-max

tests:
  fp-max-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - fp-max
